/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'app-users': AppUserAuthOperations;
  };
  blocks: {};
  collections: {
    'app-users': AppUser;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    'admin-invitations': AdminInvitation;
    media: Media;
    'user-files': UserFile;
    addresses: Address;
    'filament-types': FilamentType;
    'printing-pricing': PrintingPricing;
    'printing-options': PrintingOption;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'app-users': {
      account: 'accounts';
      session: 'sessions';
    };
  };
  collectionsSelect: {
    'app-users': AppUsersSelect<false> | AppUsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    'admin-invitations': AdminInvitationsSelect<false> | AdminInvitationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'user-files': UserFilesSelect<false> | UserFilesSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    'filament-types': FilamentTypesSelect<false> | FilamentTypesSelect<true>;
    'printing-pricing': PrintingPricingSelect<false> | PrintingPricingSelect<true>;
    'printing-options': PrintingOptionsSelect<false> | PrintingOptionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'courier-settings': CourierSetting;
  };
  globalsSelect: {
    'courier-settings': CourierSettingsSelect<false> | CourierSettingsSelect<true>;
  };
  locale: null;
  user: AppUser & {
    collection: 'app-users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AppUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-users".
 */
export interface AppUser {
  id: string;
  /**
   * Users chosen display name
   */
  name: string;
  /**
   * The email of the user
   */
  email: string;
  /**
   * Whether the email of the user has been verified
   */
  emailVerified: boolean;
  /**
   * The image of the user
   */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
  /**
   * The role/ roles of the user
   */
  role?: ('admin' | 'user')[] | null;
  /**
   * Whether the user is banned from the platform
   */
  banned?: boolean | null;
  /**
   * The reason for the ban
   */
  banReason?: string | null;
  /**
   * The date and time when the ban will expire
   */
  banExpires?: string | null;
  account?: {
    docs?: (string | Account)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  session?: {
    docs?: (string | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  phoneNumber?: string | null;
}
/**
 * Accounts are used to store user accounts for authentication providers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  /**
   * The id of the account as provided by the SSO or equal to userId for credential accounts
   */
  accountId: string;
  /**
   * The id of the provider as provided by the SSO
   */
  providerId: string;
  /**
   * The user that the account belongs to
   */
  user: string | AppUser;
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken?: string | null;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken?: string | null;
  /**
   * The id token for the account. Returned by the provider
   */
  idToken?: string | null;
  /**
   * The date and time when the access token will expire
   */
  accessTokenExpiresAt?: string | null;
  /**
   * The date and time when the refresh token will expire
   */
  refreshTokenExpiresAt?: string | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope?: string | null;
  /**
   * The hashed password of the account. Mainly used for email and password authentication
   */
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Sessions are active sessions for users. They are used to authenticate users with a session token
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  /**
   * The date and time when the session will expire
   */
  expiresAt: string;
  /**
   * The unique session token
   */
  token: string;
  createdAt: string;
  updatedAt: string;
  /**
   * The IP address of the device
   */
  ipAddress?: string | null;
  /**
   * The user agent information of the device
   */
  userAgent?: string | null;
  /**
   * The user that the session belongs to
   */
  user: string | AppUser;
  /**
   * The admin who is impersonating this session
   */
  impersonatedBy?: (string | null) | AppUser;
}
/**
 * Verifications are used to verify authentication requests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: string;
  /**
   * The identifier of the verification request
   */
  identifier: string;
  /**
   * The value to be verified
   */
  value: string;
  /**
   * The date and time when the verification request will expire
   */
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations".
 */
export interface AdminInvitation {
  id: string;
  role: 'admin' | 'user';
  token: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-files".
 */
export interface UserFile {
  id: string;
  fileType?: ('stl' | 'obj' | 'glb' | 'fbx' | 'other') | null;
  description?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  user: string | AppUser;
  recipientName: string;
  phoneNumber: string;
  addressLine1: string;
  /**
   * House number, RT, RW (optional)
   */
  addressLine2?: string | null;
  provinceCode: string;
  regencyCode: string;
  districtCode: string;
  villageCode: string;
  postalCode: string;
  isDefault?: boolean | null;
  /**
   * Location ID from RajaOngkir API (auto-populated when address is saved)
   */
  rajaOngkirDestinationId?: number | null;
  /**
   * Full location label from RajaOngkir for verification
   */
  rajaOngkirLocationLabel?: string | null;
  /**
   * Zip code from RajaOngkir (may differ from user input)
   */
  rajaOngkirZipCode?: string | null;
  /**
   * Last time RajaOngkir location was verified
   */
  rajaOngkirLastVerified?: string | null;
  /**
   * Province name from RajaOngkir
   */
  rajaOngkirProvinceName?: string | null;
  /**
   * City name from RajaOngkir
   */
  rajaOngkirCityName?: string | null;
  /**
   * District name from RajaOngkir
   */
  rajaOngkirDistrictName?: string | null;
  /**
   * Subdistrict name from RajaOngkir
   */
  rajaOngkirSubdistrictName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filament-types".
 */
export interface FilamentType {
  id: string;
  /**
   * e.g., PLA, PETG, TPU, ASA, ABS
   */
  name: string;
  colors?:
    | {
        name: string;
        /**
         * Optional: Hex code for color display (e.g., #FF0000)
         */
        hexCode?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to hide this filament type from users
   */
  isActive?: boolean | null;
  /**
   * Optional description of this filament type
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printing-pricing".
 */
export interface PrintingPricing {
  id: string;
  /**
   * Select the filament type
   */
  filamentType: string | FilamentType;
  /**
   * Add layer heights and their corresponding prices per gram
   */
  pricingTable: {
    /**
     * e.g., 0.08, 0.12, 0.16, 0.20, 0.24, 0.28
     */
    layerHeight: number;
    /**
     * Price in Indonesian Rupiah per gram
     */
    pricePerGram: number;
    id?: string | null;
  }[];
  /**
   * Uncheck to hide this pricing option from users
   */
  isActive?: boolean | null;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printing-options".
 */
export interface PrintingOption {
  id: string;
  /**
   * The type of printing option
   */
  type: 'infill' | 'wallCount';
  values?:
    | {
        /**
         * e.g., "20%" or "0.12mm"
         */
        label: string;
        /**
         * The actual value (e.g., "20" for 20%, "0.12" for layer height)
         */
        value: string;
        /**
         * Uncheck to hide this option from users
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * For numeric options like wall count, set the maximum allowed value
   */
  maxValue?: number | null;
  /**
   * Uncheck to hide this option set from users
   */
  isActive?: boolean | null;
  /**
   * Optional description of this option
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  user: string | AppUser;
  status:
    | 'unpaid'
    | 'in-review'
    | 'needs-discussion'
    | 'printing'
    | 'shipping'
    | 'in-delivery'
    | 'delivered'
    | 'completed'
    | 'canceled';
  items: {
    file: string | UserFile;
    fileName: string;
    quantity: number;
    configuration: {
      material: string;
      layerHeight: string;
      infill: string;
      wallCount: string;
    };
    statistics?: {
      /**
       * Print time in minutes
       */
      printTime?: number | null;
      /**
       * Filament weight in grams
       */
      filamentWeight?: number | null;
    };
    price: number;
    id?: string | null;
  }[];
  totalAmount: number;
  paymentInfo?: {
    paymentMethod?: ('bank_transfer' | 'credit_card' | 'e_wallet') | null;
    paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
    transactionId?: string | null;
    paidAt?: string | null;
  };
  shippingAddress?: (string | null) | Address;
  trackingNumber?: string | null;
  /**
   * Internal notes for admin use, especially for needs-discussion status
   */
  adminNotes?: string | null;
  /**
   * Notes from customer about the order
   */
  customerNotes?: string | null;
  statusHistory?:
    | {
        status: string;
        changedAt: string;
        changedBy?: (string | null) | AppUser;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'app-users';
        value: string | AppUser;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: string | Verification;
      } | null)
    | ({
        relationTo: 'admin-invitations';
        value: string | AdminInvitation;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'user-files';
        value: string | UserFile;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'filament-types';
        value: string | FilamentType;
      } | null)
    | ({
        relationTo: 'printing-pricing';
        value: string | PrintingPricing;
      } | null)
    | ({
        relationTo: 'printing-options';
        value: string | PrintingOption;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'app-users';
    value: string | AppUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'app-users';
    value: string | AppUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-users_select".
 */
export interface AppUsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  emailVerified?: T;
  image?: T;
  createdAt?: T;
  updatedAt?: T;
  role?: T;
  banned?: T;
  banReason?: T;
  banExpires?: T;
  account?: T;
  session?: T;
  phoneNumber?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  createdAt?: T;
  updatedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  impersonatedBy?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations_select".
 */
export interface AdminInvitationsSelect<T extends boolean = true> {
  role?: T;
  token?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-files_select".
 */
export interface UserFilesSelect<T extends boolean = true> {
  fileType?: T;
  description?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  recipientName?: T;
  phoneNumber?: T;
  addressLine1?: T;
  addressLine2?: T;
  provinceCode?: T;
  regencyCode?: T;
  districtCode?: T;
  villageCode?: T;
  postalCode?: T;
  isDefault?: T;
  rajaOngkirDestinationId?: T;
  rajaOngkirLocationLabel?: T;
  rajaOngkirZipCode?: T;
  rajaOngkirLastVerified?: T;
  rajaOngkirProvinceName?: T;
  rajaOngkirCityName?: T;
  rajaOngkirDistrictName?: T;
  rajaOngkirSubdistrictName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filament-types_select".
 */
export interface FilamentTypesSelect<T extends boolean = true> {
  name?: T;
  colors?:
    | T
    | {
        name?: T;
        hexCode?: T;
        id?: T;
      };
  isActive?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printing-pricing_select".
 */
export interface PrintingPricingSelect<T extends boolean = true> {
  filamentType?: T;
  pricingTable?:
    | T
    | {
        layerHeight?: T;
        pricePerGram?: T;
        id?: T;
      };
  isActive?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printing-options_select".
 */
export interface PrintingOptionsSelect<T extends boolean = true> {
  type?: T;
  values?:
    | T
    | {
        label?: T;
        value?: T;
        isActive?: T;
        id?: T;
      };
  maxValue?: T;
  isActive?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  status?: T;
  items?:
    | T
    | {
        file?: T;
        fileName?: T;
        quantity?: T;
        configuration?:
          | T
          | {
              material?: T;
              layerHeight?: T;
              infill?: T;
              wallCount?: T;
            };
        statistics?:
          | T
          | {
              printTime?: T;
              filamentWeight?: T;
            };
        price?: T;
        id?: T;
      };
  totalAmount?: T;
  paymentInfo?:
    | T
    | {
        paymentMethod?: T;
        paymentStatus?: T;
        transactionId?: T;
        paidAt?: T;
      };
  shippingAddress?: T;
  trackingNumber?: T;
  adminNotes?: T;
  customerNotes?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure shipping couriers and warehouse settings for RajaOngkir
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courier-settings".
 */
export interface CourierSetting {
  id: string;
  /**
   * Your warehouse location ID from RajaOngkir (origin for shipping calculations)
   */
  warehouseId: number;
  /**
   * Name/label for your warehouse location (for reference)
   */
  warehouseName?: string | null;
  /**
   * Full warehouse address (for reference)
   */
  warehouseAddress?: string | null;
  /**
   * Select all courier services you want to offer. These will be available during checkout.
   */
  enabledCouriers: (
    | 'jne'
    | 'jnt'
    | 'sicepat'
    | 'ide'
    | 'sap'
    | 'ninja'
    | 'tiki'
    | 'lion'
    | 'anteraja'
    | 'pos'
    | 'ncs'
    | 'rex'
    | 'rpx'
    | 'sentral'
    | 'star'
    | 'wahana'
    | 'dse'
  )[];
  /**
   * Drag to reorder how couriers appear in checkout (optional - defaults to alphabetical)
   */
  courierDisplayOrder?:
    | {
        courier:
          | 'jne'
          | 'jnt'
          | 'sicepat'
          | 'ide'
          | 'sap'
          | 'ninja'
          | 'tiki'
          | 'lion'
          | 'anteraja'
          | 'pos'
          | 'ncs'
          | 'rex'
          | 'rpx'
          | 'sentral'
          | 'star'
          | 'wahana'
          | 'dse';
        /**
         * Lower numbers appear first (1 = highest priority)
         */
        priority?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Minimum order value for free shipping (set to 0 to disable free shipping)
   */
  freeShippingThreshold?: number | null;
  /**
   * Which courier service to pre-select in checkout (optional)
   */
  defaultShippingService?: ('' | 'jne' | 'jnt' | 'sicepat') | null;
  /**
   * How many days it takes to process orders before shipping (added to courier delivery time)
   */
  estimatedProcessingDays: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courier-settings_select".
 */
export interface CourierSettingsSelect<T extends boolean = true> {
  warehouseId?: T;
  warehouseName?: T;
  warehouseAddress?: T;
  enabledCouriers?: T;
  courierDisplayOrder?:
    | T
    | {
        courier?: T;
        priority?: T;
        id?: T;
      };
  freeShippingThreshold?: T;
  defaultShippingService?: T;
  estimatedProcessingDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}